server:
  port: 8761

spring:
  application:
    name: discovery-server
  # CHANGED: Add compatibility verifier disable for all services
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO